package Dtos;
// Generated 8 ene 2025, 21:07:46 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private short doctorNo;
	private String apellido;
	private String especialidad;
	private Set hospitaleses = new HashSet(0);

	public Doctor() {
	}

	public Doctor(short doctorNo) {
		this.doctorNo = doctorNo;
	}

	public Doctor(short doctorNo, String apellido, String especialidad, Set hospitaleses) {
		this.doctorNo = doctorNo;
		this.apellido = apellido;
		this.especialidad = especialidad;
		this.hospitaleses = hospitaleses;
	}

	public short getDoctorNo() {
		return this.doctorNo;
	}

	public void setDoctorNo(short doctorNo) {
		this.doctorNo = doctorNo;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Set getHospitaleses() {
		return this.hospitaleses;
	}

	public void setHospitaleses(Set hospitaleses) {
		this.hospitaleses = hospitaleses;
	}

}
