package Dtos;
// Generated 8 ene 2025, 21:07:46 by Hibernate Tools 5.6.15.Final

/**
 * ResumenHospitales generated by hbm2java
 */
public class ResumenHospitales implements java.io.Serializable {

	private byte hospitalCod;
	private Hospitales hospitales;
	private Short numDoctores;
	private Short numSalas;
	private Short numEnfermos;
	private Short numPlantilla;

	public ResumenHospitales() {
	}

	public ResumenHospitales(Hospitales hospitales) {
		this.hospitales = hospitales;
	}

	public ResumenHospitales(Hospitales hospitales, Short numDoctores, Short numSalas, Short numEnfermos,
			Short numPlantilla) {
		this.hospitales = hospitales;
		this.numDoctores = numDoctores;
		this.numSalas = numSalas;
		this.numEnfermos = numEnfermos;
		this.numPlantilla = numPlantilla;
	}

	public byte getHospitalCod() {
		return this.hospitalCod;
	}

	public void setHospitalCod(byte hospitalCod) {
		this.hospitalCod = hospitalCod;
	}

	public Hospitales getHospitales() {
		return this.hospitales;
	}

	public void setHospitales(Hospitales hospitales) {
		this.hospitales = hospitales;
	}

	public Short getNumDoctores() {
		return this.numDoctores;
	}

	public void setNumDoctores(Short numDoctores) {
		this.numDoctores = numDoctores;
	}

	public Short getNumSalas() {
		return this.numSalas;
	}

	public void setNumSalas(Short numSalas) {
		this.numSalas = numSalas;
	}

	public Short getNumEnfermos() {
		return this.numEnfermos;
	}

	public void setNumEnfermos(Short numEnfermos) {
		this.numEnfermos = numEnfermos;
	}

	public Short getNumPlantilla() {
		return this.numPlantilla;
	}

	public void setNumPlantilla(Short numPlantilla) {
		this.numPlantilla = numPlantilla;
	}

}
