package Dtos;
// Generated 5 ene 2025, 21:02:14 by Hibernate Tools 5.6.15.Final

/**
 * NuevasSalas generated by hbm2java
 */
public class NuevasSalas implements java.io.Serializable {

	private NuevasSalasId id;

	public NuevasSalas() {
	}

	public NuevasSalas(NuevasSalasId id) {
		this.id = id;
	}

	public NuevasSalasId getId() {
		return this.id;
	}

	public void setId(NuevasSalasId id) {
		this.id = id;
	}

}
