package Dtos;
// Generated 5 ene 2025, 21:02:14 by Hibernate Tools 5.6.15.Final

/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion implements java.io.Serializable {

	private OcupacionId id;
	private Hospitales hospitales;
	private Sala sala;
	private Enfermo enfermo;
	private Short cama;

	public Ocupacion() {
	}

	public Ocupacion(OcupacionId id, Hospitales hospitales, Sala sala, Enfermo enfermo) {
		this.id = id;
		this.hospitales = hospitales;
		this.sala = sala;
		this.enfermo = enfermo;
	}

	public Ocupacion(OcupacionId id, Hospitales hospitales, Sala sala, Enfermo enfermo, Short cama) {
		this.id = id;
		this.hospitales = hospitales;
		this.sala = sala;
		this.enfermo = enfermo;
		this.cama = cama;
	}

	public OcupacionId getId() {
		return this.id;
	}

	public void setId(OcupacionId id) {
		this.id = id;
	}

	public Hospitales getHospitales() {
		return this.hospitales;
	}

	public void setHospitales(Hospitales hospitales) {
		this.hospitales = hospitales;
	}

	public Sala getSala() {
		return this.sala;
	}

	public void setSala(Sala sala) {
		this.sala = sala;
	}

	public Enfermo getEnfermo() {
		return this.enfermo;
	}

	public void setEnfermo(Enfermo enfermo) {
		this.enfermo = enfermo;
	}

	public Short getCama() {
		return this.cama;
	}

	public void setCama(Short cama) {
		this.cama = cama;
	}

}
